// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, test, vi } from "vitest";

// Stub the IDB layer with an in-memory fake. The wrapping key is a real
// CryptoKey generated by jsdom's WebCrypto, so encryption/decryption is
// genuine — only the persistence boundary is faked.
const idbValues = new Map<string, unknown>();
vi.mock("../storage/idbStorage", () => ({
  idbStorage: {
    get: vi.fn(async (_db: unknown, _store: string, key: string) => idbValues.get(key)),
    put: vi.fn(async (_db: unknown, _store: string, value: unknown, key: string) => {
      idbValues.set(key, value);
    }),
    delete: vi.fn(async (_db: unknown, _store: string, key: string) => {
      idbValues.delete(key);
    }),
  },
}));
vi.mock("../storage/taskifyDb", async () => {
  const actual = await vi.importActual<typeof import("../storage/taskifyDb")>("../storage/taskifyDb");
  return { ...actual, getTaskifyDb: vi.fn(async () => ({} as IDBDatabase)) };
});

import {
  __resetForTests,
  clearSk,
  getSkSync,
  init,
  isLoaded,
  LS_NOSTR_SK_V2,
  setSk,
} from "./nostrSkStore";
import { kvStorage } from "../storage/kvStorage";
import { LS_NOSTR_SK as LS_NOSTR_SK_V1 } from "../nostrKeys";

const SAMPLE_SK = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";

beforeEach(() => {
  // Fresh state between tests
  idbValues.clear();
  kvStorage.removeItem(LS_NOSTR_SK_V1);
  kvStorage.removeItem(LS_NOSTR_SK_V2);
  __resetForTests();
});
afterEach(() => {
  idbValues.clear();
  kvStorage.removeItem(LS_NOSTR_SK_V1);
  kvStorage.removeItem(LS_NOSTR_SK_V2);
});

describe("nostrSkStore", () => {
  test("init with no existing SK leaves cache empty", async () => {
    await init();
    expect(isLoaded()).toBe(true);
    expect(getSkSync()).toBe("");
    expect(kvStorage.getItem(LS_NOSTR_SK_V1)).toBeNull();
    expect(kvStorage.getItem(LS_NOSTR_SK_V2)).toBeNull();
  });

  test("setSk writes ciphertext (not plaintext) to localStorage", async () => {
    await init();
    await setSk(SAMPLE_SK);
    expect(getSkSync()).toBe(SAMPLE_SK);
    const v2 = kvStorage.getItem(LS_NOSTR_SK_V2);
    expect(v2).toBeTruthy();
    expect(v2).not.toBe(SAMPLE_SK);
    expect(v2).not.toContain(SAMPLE_SK);
    expect(kvStorage.getItem(LS_NOSTR_SK_V1)).toBeNull();
  });

  test("init decrypts an existing v2 ciphertext", async () => {
    await init();
    await setSk(SAMPLE_SK);
    const persistedV2 = kvStorage.getItem(LS_NOSTR_SK_V2);
    expect(persistedV2).toBeTruthy();

    // Simulate fresh app load: keep idbValues + ciphertext, reset module cache
    __resetForTests();
    expect(getSkSync()).toBe("");

    await init();
    expect(getSkSync()).toBe(SAMPLE_SK);
  });

  test("migrates v1 plaintext → v2 ciphertext and removes v1", async () => {
    kvStorage.setItem(LS_NOSTR_SK_V1, SAMPLE_SK);
    await init();
    expect(getSkSync()).toBe(SAMPLE_SK);
    expect(kvStorage.getItem(LS_NOSTR_SK_V1)).toBeNull();
    const v2 = kvStorage.getItem(LS_NOSTR_SK_V2);
    expect(v2).toBeTruthy();
    expect(v2).not.toContain(SAMPLE_SK);
  });

  test("init is idempotent across concurrent calls", async () => {
    kvStorage.setItem(LS_NOSTR_SK_V1, SAMPLE_SK);
    const [a, b, c] = await Promise.all([init(), init(), init()]);
    expect(a).toBeUndefined();
    expect(b).toBeUndefined();
    expect(c).toBeUndefined();
    expect(getSkSync()).toBe(SAMPLE_SK);
    // v1 was migrated exactly once: v1 gone, v2 set
    expect(kvStorage.getItem(LS_NOSTR_SK_V1)).toBeNull();
    expect(kvStorage.getItem(LS_NOSTR_SK_V2)).toBeTruthy();
  });

  test("clearSk removes both v1 and v2 and empties the cache", async () => {
    kvStorage.setItem(LS_NOSTR_SK_V1, SAMPLE_SK);
    await init();
    expect(getSkSync()).toBe(SAMPLE_SK);
    await clearSk();
    expect(getSkSync()).toBe("");
    expect(kvStorage.getItem(LS_NOSTR_SK_V1)).toBeNull();
    expect(kvStorage.getItem(LS_NOSTR_SK_V2)).toBeNull();
  });

  test("ciphertexts use a fresh IV each time (different output for same input)", async () => {
    await init();
    await setSk(SAMPLE_SK);
    const first = kvStorage.getItem(LS_NOSTR_SK_V2);
    await setSk(SAMPLE_SK);
    const second = kvStorage.getItem(LS_NOSTR_SK_V2);
    expect(first).toBeTruthy();
    expect(second).toBeTruthy();
    expect(first).not.toBe(second);
  });

  test("setSk with empty string clears the SK", async () => {
    await init();
    await setSk(SAMPLE_SK);
    expect(getSkSync()).toBe(SAMPLE_SK);
    await setSk("");
    expect(getSkSync()).toBe("");
    expect(kvStorage.getItem(LS_NOSTR_SK_V2)).toBeNull();
  });
});
